update yml file

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -36,23 +36,35 @@ jobs:
 
       - name: Execute Tests on Windows Edge
         continue-on-error: true
-        run: mvn test "-DbrowserName=edge" "-Dallure.results.directory=target/allure-results" "-DheadLessExecution=false" "-Dtest=${{ github.event.inputs.testsPath }}"
+        run: mvn test "-DbrowserName=edge" "-DheadLessExecution=false" "-Dtest=${{ github.event.inputs.testsPath }}"
 
-      - name: Upload Allure Results
-        uses: actions/upload-artifact@v4
+      - name: Generate Allure Report
+        continue-on-error: true
+        run: mvn allure:report
+
+      - name: Upload Allure Report
+        uses: actions/upload-artifact@v3
         with:
-          name: Allure-Report-Edge-Windows
-          path: target/allure-results
+          name: Allure Report Ubuntu Chrome
+          path: target/site/allure-maven-plugin/index.html
+
+  #      - name: Upload Allure Results
+  #        uses: actions/upload-artifact@v4
+  #        with:
+  #          name: Allure-Report-Edge-Windows
+  #          path: target/allure-results
+
+
 
 
   #      - name: Publish Test Results for Windows Edge
-#        continue-on-error: true
-#        uses: dorny/test-reporter@v1
-#        if: success() || failure()
-#        with:
-#          name: Tests Report Windows-Edge
-#          path: 'target/surefire-reports/TEST-*.xml'
-#          reporter: java-junit
+  #        continue-on-error: true
+  #        uses: dorny/test-reporter@v1
+  #        if: success() || failure()
+  #        with:
+  #          name: Tests Report Windows-Edge
+  #          path: 'target/surefire-reports/TEST-*.xml'
+  #          reporter: java-junit
 
   E2E_TestUbuntu:
     runs-on: ubuntu-latest
@@ -76,13 +88,23 @@ jobs:
 
       - name: Execute Tests on Ubuntu Chrome
         continue-on-error: true
-        run: mvn test "-DbrowserName=chrome" "-Dallure.results.directory=target/allure-results" "-DheadLessExecution=true" "-Dtest=${{ github.event.inputs.testsPath }}"
+        run: mvn test "-DbrowserName=chrome" "-DheadLessExecution=true" "-Dtest=${{ github.event.inputs.testsPath }}"
 
-      - name: Upload Allure Results
-        uses: actions/upload-artifact@v4
+
+      - name: Generate Allure Report
+        continue-on-error: true
+        run: mvn allure:report
+
+      - name: Upload Allure Report
+        uses: actions/upload-artifact@v3
         with:
-            name: Allure-Report-Edge-Windows
-            path: target/allure-results
+          name: Allure Report Ubuntu Chrome
+          path: target/site/allure-maven-plugin/index.html
+#      - name: Upload Allure Results
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: Allure-Report-Edge-Windows
+#          path: target/allure-results
 
 #      - name: Generate Allure Report
 #        continue-on-error: true
